### ISSUE TITLE
Fail on reldi_tokeniser import

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/classla-stanfordnlp#19]
I tried to use the classla pipeline (on Ubuntu 20.04.2 LTS), starting with the simple ` $ python3 pipeline_demo.py`.
It got the models ok, as well as some further steps but then it can't find reldi_tokeniser:
```
2021-05-19 16:32:13 INFO: Use device: cpu
2021-05-19 16:32:13 INFO: Loading: tokenize
Traceback (most recent call last):
  File "pipeline_demo.py", line 37, in <module>
    pipeline = classla.Pipeline(dir=args.models_dir, lang=args.lang, use_gpu=(not args.cpu))
  File "/usr/local/classla/classla/pipeline/core.py", line 114, in __init__
    use_gpu=self.use_gpu)
  File "/usr/local/classla/classla/pipeline/processor.py", line 146, in __init__
    self._set_up_model(config, use_gpu)
  File "/usr/local/classla/classla/pipeline/tokenize_processor.py", line 32, in _set_up_model
    self._tokenizer = ObeliksTrainer(config.get('lang'), config.get('type'))
  File "/usr/local/classla/classla/utils/obeliks.py", line 32, in __init__
    from classla.submodules.reldi_tokeniser import tokeniser
ImportError: cannot import name 'tokeniser' from 'classla.submodules.reldi_tokeniser' (unknown location)
```

Any idea what went wrong here?

**Comment by nljubesi** [comment]
Could you give the deets on the install?

What you should have done, and what should work, is a simple "pip install classla" from a folder where there is no "classla" subfolder.

**Comment by TomazErjavec** [comment]
> What you should have done, and what should work, is a simple "pip install classla" from a folder where there is no "classla" subfolder.

I think I did exactly that. But, to be on the safe side, I now `pip uninstall classla` and also deleted the models. Then:
```
tomaz@new-tantra ~$ pip install classla
Collecting classla
  Downloading classla-1.0.1-py3-none-any.whl (259 kB)
     |████████████████████████████████| 259 kB 6.4 MB/s
Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (from classla) (1.20.1)
Requirement already satisfied: tqdm in ./.local/lib/python3.8/site-packages (from classla) (4.56.2)
Processing ./.cache/pip/wheels/61/31/e3/03bb904718d6ef2e12041f62866b28c0e300ce54518908cccd/obeliks-1.0.5-py3-n\
one-any.whl
Requirement already satisfied: torch>=1.3.0 in ./.local/lib/python3.8/site-packages (from classla) (1.5.0)
Requirement already satisfied: protobuf in ./.local/lib/python3.8/site-packages (from classla) (3.14.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from classla) (2.22.0)
Requirement already satisfied: lxml in ./.local/lib/python3.8/site-packages (from obeliks->classla) (4.5.2)
Requirement already satisfied: regex in ./.local/lib/python3.8/site-packages (from obeliks->classla) (2020.10.\
28)
Requirement already satisfied: future in ./.local/lib/python3.8/site-packages (from torch>=1.3.0->classla) (0.\
18.2)
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from protobuf->classla) (1.14.0)
Installing collected packages: obeliks, classla
Successfully installed classla-1.0.1 obeliks-1.0.5
tomaz@new-tantra ~$ cd /usr/local/classla/
/usr/local/classla
tomaz@new-tantra classla$ python3 pipeline_demo.py
Downloading https://raw.githubusercontent.com/clarinsi/classla-resources/main/resources_1.0.0.json: 10.3kB [00:00, 6.50MB/s]
2021-05-19 17:07:54 INFO: Downloading these customized packages for language: sl (Slovenian)...
========================
| Processor | Package  |
------------------------
| tokenize  | standard |
| pos       | standard |
| lemma     | standard |
| depparse  | standard |
| ner       | standard |
| pretrain  | standard |
========================
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1391/ssj500k: 100%|█| 118M/118M [00:
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1412/sl_all_Sloleks_lemmatizer.pt: 1
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1258/ssj500k_ud: 100%|█| 96.0M/96.0M
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1321/ssj500k: 100%|█| 48.3M/48.3M [0
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1391/ssj500k.pretrain.pt: 100%|█| 11
2021-05-19 17:08:01 INFO: Finished downloading models and saved to /home/tomaz/classla_resources.
---
Building pipeline...
2021-05-19 17:08:01 INFO: Loading these models for language: sl (Slovenian):
========================
| Processor | Package  |
------------------------
| tokenize  | standard |
| pos       | standard |
| lemma     | standard |
| depparse  | standard |
| ner       | standard |
========================

2021-05-19 17:08:01 INFO: Use device: cpu
2021-05-19 17:08:01 INFO: Loading: tokenize
Traceback (most recent call last):
  File "pipeline_demo.py", line 37, in <module>
    pipeline = classla.Pipeline(dir=args.models_dir, lang=args.lang, use_gpu=(not args.cpu))
  File "/usr/local/classla/classla/pipeline/core.py", line 112, in __init__
    self.processors[processor_name] = NAME_TO_PROCESSOR_CLASS[processor_name](config=curr_processor_config,
  File "/usr/local/classla/classla/pipeline/processor.py", line 146, in __init__
    self._set_up_model(config, use_gpu)
  File "/usr/local/classla/classla/pipeline/tokenize_processor.py", line 32, in _set_up_model
    self._tokenizer = ObeliksTrainer(config.get('lang'), config.get('type'))
  File "/usr/local/classla/classla/utils/obeliks.py", line 32, in __init__
    from classla.submodules.reldi_tokeniser import tokeniser
ImportError: cannot import name 'tokeniser' from 'classla.submodules.reldi_tokeniser' (unknown location)
```

This was done directly on the sys-wide python, so, not using conda. No idea if that is a problem (but I also tried with active conda, and got the same result).

**Comment by nljubesi** [comment]
This might be a pipeline_demo.py script issue. Loading the pipeline works as expected, but running the pipeline_demo.py script fails as @TomazErjavec described. @lkrsnik, could you have a look?

**Comment by lkrsnik** [comment]
Which files do you have in `/usr/local/classla/`? It looks to me as if you cloned classla repository to this location. If you have `/usr/local/classla/classla` folder in there, python will use those local files before it uses the actual library you installed. A solution would be to either remove nested classla folder or move pipeline_demo.py.

**Comment by TomazErjavec** [comment]
> Which files do you have in /usr/local/classla/? It looks to me as if you cloned classla repository to this location.

Yes, exactly.

> If you have /usr/local/classla/classla folder in there, python will use those local files before it uses the actual library you installed.

I see! OK, it makes sense in retrospect, but maybe it would worth adding a note about that in the installation part of the readme. As otherwise others might make the same mistake, after all, if you want to test the pipeline with the demo script, you have to clone the repository, and then it is natural to just try and run the demo script, rather than being smart enough to first move it somewhere else.

> A solution would be to either remove nested classla folder or move pipeline_demo.py.

I moved the pipeline_demo.py and indeed, it works just fine now, thanks. So, closing the issue, and leaving it to your discretion to comment about this in the readem.

**Comment by nljubesi** [comment]
I agree with @TomazErjavec, having a script in a location where it will never work is just absurd. I suggest we move the pipeline_demo.py file to a demo folder.

**Comment by nljubesi** [comment]
Looking at the existing demo folder, I decided to

1. remove all the files from the demo folder, except for the "resources.json", which is related to our project (not sure whether this is the best location for it)
2. move the root pipeline_demo.py file to this demo folder.
