### ISSUE TITLE
Classla required resources not available

### ISSUE THREAD

**Issue by mabajec** [clarinsi/classla-stanfordnlp#42]
**Describe the bug**
Classla module not able to download resources via classla.download()

**To Reproduce**
import classla
classla.download('sl')

see error that you get

**Expected behavior**
Resources should download

**Comment by nljubesi** [comment]
This is quite likely because the CLARIN.SI repo (https://www.clarin.si/repository/xmlui/) where the models are hosted is currently experiencing issues. Should be up soon.

**Comment by h200101** [comment]
Hi!
Is this still the problem? I tried with Python 3.11 and 3.8 and the error is:
```
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1767/suk_pos: 100%|█| 425M/425M [00:30<00:00,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\usra\AppData\Local\Programs\Python\Python38\lib\site-packages\classla\resources\common.py", line 437, in download
    request_file(
  File "C:\Users\usra\AppData\Local\Programs\Python\Python38\lib\site-packages\classla\resources\common.py", line 168, in request_file
    download_file(url, path)
  File "C:\Users\usra\AppData\Local\Programs\Python\Python38\lib\site-packages\classla\resources\common.py", line 156, in download_file
    unzip_file(normal_path, path)
  File "C:\Users\usra\AppData\Local\Programs\Python\Python38\lib\site-packages\classla\resources\common.py", line 95, in unzip_file
    wf.write(rf.read(file.filename))
  File "C:\Users\usra\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1441, in read
    return fp.read()
  File "C:\Users\usra\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 893, in read
    buf += self._read1(self.MAX_N)
  File "C:\Users\usra\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 983, in _read1
    data = self._decompressor.decompress(data, n)
MemoryError```
